name: navigation_history_observer
description: A Flutter NavigatorObserver that stores a collection of pushed routes history, as well as the popped history.
version: 1.0.3+1
homepage: https://github.com/Polarts/navigation_history_observer

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  built_collection: ^5.0.0

dev_dependencies:

flutter: